PLASTIC_DETAILS = {
    "PET": {
        "name": "Polyethylene Terephthalate (PET)",
        "code": "1",
        "harmfulness": "Low (for single use)",
        "env_risk": 35,
        "carbon_footprint": "2.15 kg CO2/kg",
        "decomp_time": "450 Years",
        "recyclability": "90%",
        "disposal": "Rinse and place in blue recycling bins. Do not reuse single-use bottles.",
        "health_risk": "Can leach antimony (a potential carcinogen) if exposed to heat or stored long-term.",
        "river_impact": "Extremely high. Floats easily and is the most common plastic bottle litter in waterways.",
        "wildlife_impact": "Frequently ingested by marine life and large birds, causing digestive tract blockages.",
        "alternatives": "Glass bottles, Stainless steel flasks, copper vessels, reusable aluminum containers."
    },
    "HDPE": {
        "name": "High-Density Polyethylene (HDPE)",
        "code": "2",
        "harmfulness": "Very Low",
        "env_risk": 20,
        "carbon_footprint": "1.60 kg CO2/kg",
        "decomp_time": "100-300 Years",
        "recyclability": "85%",
        "disposal": "Place in recycling bins. HDPE is highly valued by recyclers.",
        "health_risk": "One of the safest plastics; low risk of chemical leaching into food or drinks.",
        "river_impact": "Moderate to High. Breakdown into microplastics that poison aquatic life.",
        "wildlife_impact": "Physical entrapment and choking risk for small river animals.",
        "alternatives": "Glass jars, metal containers, silicone bags, reusable cotton bags."
    },
    "PVC": {
        "name": "Polyvinyl Chloride (PVC)",
        "code": "3",
        "harmfulness": "Extremely High",
        "env_risk": 95,
        "carbon_footprint": "3.10 kg CO2/kg",
        "decomp_time": "Infinite (does not biodegrade)",
        "recyclability": "0% (Rarely recycled)",
        "disposal": "Dispose of in landfill or hazardous waste collection. Do NOT burn PVC.",
        "health_risk": "Leaches toxic chemicals (phthalates, dioxins, lead, cadmium) known to cause hormone disruption and cancer.",
        "river_impact": "Critical. Heavy and sinks, releasing toxic additives directly into riverbeds and sediments.",
        "wildlife_impact": "Releases toxic chemicals into water, poisoning aquatic species and disrupting reproduction.",
        "alternatives": "Bamboo poles, clay pipes, wooden structures, metal pipes, organic fabric."
    },
    "LDPE": {
        "name": "Low-Density Polyethylene (LDPE)",
        "code": "4",
        "harmfulness": "Low",
        "env_risk": 45,
        "carbon_footprint": "1.80 kg CO2/kg",
        "decomp_time": "500-1000 Years",
        "recyclability": "30%",
        "disposal": "Check local guidelines. Often accepted at supermarket film collection points.",
        "health_risk": "Relatively safe, but can leach estrogenic chemicals under high temperatures.",
        "river_impact": "Severe. Lightweight plastic bags easily block water channels, drains, and catchments.",
        "wildlife_impact": "Frequently ingested by marine turtles and land mammals who mistake bags for jellyfish or food.",
        "alternatives": "Canvas shopping bags, beeswax wraps, glass storage containers."
    },
    "PP": {
        "name": "Polypropylene (PP)",
        "code": "5",
        "harmfulness": "Low",
        "env_risk": 30,
        "carbon_footprint": "1.70 kg CO2/kg",
        "decomp_time": "20-30 Years (low compared to others)",
        "recyclability": "40%",
        "disposal": "Accepted in most curbside recycling programs. Ensure it is clean of food remnants.",
        "health_risk": "High heat tolerance makes it safe for hot food/drinks. Low risk of chemical leaching.",
        "river_impact": "Moderate. Tends to break down into microplastic fibers that bioaccumulate in river fish.",
        "wildlife_impact": "Microplastics ingested by filter feeders, moving up the food chain to predators.",
        "alternatives": "Stainless steel lunchboxes, ceramic mugs, wooden utensils, cloth packaging."
    },
    "PS": {
        "name": "Polystyrene (PS / Styrofoam)",
        "code": "6",
        "harmfulness": "Very High",
        "env_risk": 85,
        "carbon_footprint": "2.50 kg CO2/kg",
        "decomp_time": "500 Years",
        "recyclability": "1%",
        "disposal": "Landfill waste. Avoid using as it breaks into tiny particles easily.",
        "health_risk": "Leaches styrene, a suspected carcinogen and neurotoxin, especially when heated with hot food/drinks.",
        "river_impact": "Disastrous. Breaks into thousands of tiny buoyant balls that cover river surfaces.",
        "wildlife_impact": "Fish and birds eat the white foam balls, leading to starvation due to stomach blockage.",
        "alternatives": "Paper cups, bagasse (sugarcane fiber) plates, mushroom-based packaging, cardboard."
    },
    "Other": {
        "name": "Other (PC, Nylon, Acrylic, etc.)",
        "code": "7",
        "harmfulness": "High",
        "env_risk": 75,
        "carbon_footprint": "2.80 kg CO2/kg",
        "decomp_time": "500-1000 Years",
        "recyclability": "5%",
        "disposal": "Generally not recyclable. Toss in standard trash bins.",
        "health_risk": "Polycarbonates leach BPA (Bisphenol A), a potent endocrine disruptor that causes reproductive issues.",
        "river_impact": "High. Toxic chemical runoff from landfill leaching makes its way into local rivers.",
        "wildlife_impact": "Bioaccumulation of BPA and plasticizers affects the development of aquatic wildlife.",
        "alternatives": "BPA-free bottles, bio-plastics (PLA - but compostable only), glass, metal."
    }
}
