import os
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from fpdf import FPDF
from datetime import datetime

class EcoReportPDF(FPDF):
    def header(self):
        # Draw header banner
        self.set_fill_color(34, 197, 94) # Green-500
        self.rect(0, 0, 210, 40, 'F')
        
        self.set_text_color(255, 255, 255)
        self.set_font('Arial', 'B', 24)
        self.cell(0, 15, 'EcoSort AI', ln=True, align='C')
        self.set_font('Arial', 'I', 12)
        self.cell(0, 10, 'Smart Plastic Sustainability & Analysis Report', ln=True, align='C')
        self.ln(10)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(156, 163, 175) # Gray-400
        self.cell(0, 10, f'Generated by EcoSort AI on {datetime.now().strftime("%Y-%m-%d %H:%M")} | Page ' + str(self.page_no()), 0, 0, 'C')

def generate_pdf_report(plastic_key, confidence, detail, image_path=None):
    pdf = EcoReportPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)
    
    # Reset Text Color to Charcoal
    pdf.set_text_color(31, 41, 55) # Gray-800
    
    # Scanned Result Card
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, '1. Scan Overview', ln=True)
    pdf.ln(2)
    
    # Overview Table
    pdf.set_font('Arial', 'B', 11)
    pdf.set_fill_color(243, 244, 246) # Gray-100
    
    pdf.cell(50, 8, ' Parameter', 1, 0, 'L', True)
    pdf.cell(140, 8, ' Detected Value', 1, 1, 'L', True)
    
    pdf.set_font('Arial', '', 11)
    pdf.cell(50, 8, ' Plastic Category', 1, 0, 'L')
    pdf.cell(140, 8, f' {detail["name"]} (Code {detail["code"]})', 1, 1, 'L')
    
    pdf.cell(50, 8, ' Detection Confidence', 1, 0, 'L')
    pdf.cell(140, 8, f' {confidence:.2f}%', 1, 1, 'L')
    
    pdf.cell(50, 8, ' Harmfulness Level', 1, 0, 'L')
    pdf.cell(140, 8, f' {detail["harmfulness"]}', 1, 1, 'L')
    
    pdf.cell(50, 8, ' Environmental Risk', 1, 0, 'L')
    pdf.cell(140, 8, f' {detail["env_risk"]}/100', 1, 1, 'L')
    
    pdf.cell(50, 8, ' Est. Decomposition', 1, 0, 'L')
    pdf.cell(140, 8, f' {detail["decomp_time"]}', 1, 1, 'L')
    
    pdf.cell(50, 8, ' Recyclability Rate', 1, 0, 'L')
    pdf.cell(140, 8, f' {detail["recyclability"]}', 1, 1, 'L')
    
    pdf.ln(10)
    
    # Handle Image Embeddings Side-by-Side
    y_before_media = pdf.get_y()
    
    # Generate Matplotlib chart on the fly
    chart_path = 'temp_report_chart.png'
    fig, ax = plt.subplots(figsize=(4, 3))
    
    categories = ['Recyclability', 'Env Risk']
    # Extract numerical values
    rec_val = int(detail["recyclability"].replace('%', ''))
    env_val = detail["env_risk"]
    
    colors = ['#22c55e', '#ef4444']
    bars = ax.bar(categories, [rec_val, env_val], color=colors, width=0.5)
    ax.set_ylim(0, 100)
    ax.set_ylabel('Percentage / Score')
    ax.set_title('Eco Impact Profile')
    for bar in bars:
        yval = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2, yval + 2, f"{yval}", ha='center', va='bottom', fontweight='bold')
    
    plt.tight_layout()
    plt.savefig(chart_path, dpi=150)
    plt.close()
    
    # Add Image and Chart
    if image_path and os.path.exists(image_path):
        try:
            pdf.image(image_path, x=10, y=y_before_media, w=80, h=60)
        except Exception:
            pdf.rect(10, y_before_media, 80, 60)
            pdf.text(25, y_before_media + 30, "Image Error")
    else:
        # Create a fallback placeholder rect
        pdf.set_fill_color(229, 231, 235)
        pdf.rect(10, y_before_media, 80, 60, 'F')
        pdf.set_font('Arial', 'I', 10)
        pdf.set_text_color(107, 114, 128)
        pdf.text(25, y_before_media + 30, "No Upload Image Provided")
        pdf.set_text_color(31, 41, 55)
        
    # Embed Chart
    if os.path.exists(chart_path):
        pdf.image(chart_path, x=110, y=y_before_media, w=90, h=60)
        
    pdf.set_y(y_before_media + 65)
    pdf.ln(5)
    
    # 2. Detailed Sustainability Analysis
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, '2. Detailed Sustainability & Impact Analysis', ln=True)
    pdf.ln(2)
    
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 6, 'Carbon Footprint Estimate:', ln=True)
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 6, f'Approximately {detail["carbon_footprint"]} is generated during the production and transport of this type of plastic material.')
    pdf.ln(2)
    
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 6, 'Human Health Risks:', ln=True)
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 6, detail["health_risk"])
    pdf.ln(2)
    
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 6, 'River & Aquatic Systems Impact:', ln=True)
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 6, detail["river_impact"])
    pdf.ln(2)
    
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 6, 'Wildlife & Ecosystem Harm:', ln=True)
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 6, detail["wildlife_impact"])
    pdf.ln(5)
    
    # 3. Actionable Recommendations
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, '3. Actionable Recommendations', ln=True)
    pdf.ln(2)
    
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 6, 'Suggested Disposal Method:', ln=True)
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 6, detail["disposal"])
    pdf.ln(2)
    
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 6, 'Sustainable Alternative Materials:', ln=True)
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 6, detail["alternatives"])
    pdf.ln(4)
    
    # Government & Educational Note
    pdf.set_fill_color(220, 252, 231) # Green-100
    pdf.rect(10, pdf.get_y(), 190, 20, 'F')
    pdf.set_y(pdf.get_y() + 2)
    pdf.set_font('Arial', 'B', 9)
    pdf.set_text_color(22, 101, 52) # Green-800
    pdf.cell(0, 5, '   EDUCATIONAL & POLICY NOTICE', ln=True)
    pdf.set_font('Arial', 'I', 9)
    pdf.multi_cell(0, 5, '   "Every piece of plastic correctly recycled helps protect nature." Make sure to follow the Extended\n   Producer Responsibility (EPR) guidelines and Swachh Bharat recycling rules in your locality.')
    
    # Clean up temporary chart file
    try:
        if os.path.exists(chart_path):
            os.remove(chart_path)
    except Exception:
        pass
        
    output_filename = f'report_{plastic_key}_{datetime.now().strftime("%Y%m%d%H%M%S")}.pdf'
    pdf.output(output_filename, 'F')
    return output_filename
